name    'puppet-minecraft'
version '2.0.2'
source  'https://github.com/branan/puppet-module-minecraft'
author  'Branan Purvine-Riley, Andrew Schwartzmeyer'
license 'Apache License 2.0'
summary 'Minecraft / CraftBukkit Server'
description 'Install and manage a Minecraft or CraftBukkit server'
project_page 'https://github.com/branan/puppet-module-minecraft'

dependency 'maestrodev/wget', '>= 1.1.0'
dependency 'puppetlabs/java', '>= 0.1.6'
