name    'branan-minecraft'
version '0.1.1'
source  'https://github.com/branan/puppet-minecraft'
author  'Branan Purvine-Riley'
license 'Apache License 2.0'
summary 'Minecraft Server'
description 'Install and manage a Minecraft server'
project_page 'https://github.com/branan/puppet-minecraft'

dependency 'puppetlabs/stdlib', '>= 2.2.0'
dependency 'branan/s3file', '>= 0.5.0'
dependency 'puppetlabs/java', '>= 0.1.6'
